app = "kirana-backend"  # your app name on Fly.io

primary_region = "bom"  # Mumbai (or use "sin" for Singapore if Mumbai fails)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[vm]
  size = "shared-cpu-1x"
  memory = 256
